import { NgModule } from '@angular/core';
import {
	MatButtonModule, MatCardModule, MatCheckboxModule,
	MatDatepickerModule, MatDialogModule,
	MatDividerModule, MatError, MatFormFieldModule, MatIconModule, MatInputModule, MatListModule,
	MatNativeDateModule, MatPaginatorModule, MatProgressSpinnerModule,
	MatRadioModule,
	MatSelectModule, MatSidenavModule,
	MatSliderModule, MatSnackBarModule, MatSortModule, MatTableModule,
	MatTabsModule, MatToolbarModule, MatExpansionModule, MatMenuModule, MatChipsModule, MatButtonToggleModule
} from "@angular/material";

@NgModule({
	imports: [
		MatIconModule,
		MatButtonModule,
		MatSidenavModule,
		MatDialogModule,
		MatChipsModule,
		MatListModule,
		MatTabsModule,
		MatDividerModule,
		MatSliderModule,
		MatSelectModule,
		MatRadioModule,
		MatNativeDateModule,
		MatDatepickerModule,
		MatSnackBarModule,
		MatIconModule,
		MatDialogModule,
		MatProgressSpinnerModule,
		MatButtonModule,
		MatSortModule,
		MatTableModule,
		MatTabsModule,
		MatCheckboxModule,
		MatToolbarModule,
		MatCardModule,
		MatButtonToggleModule,
		MatFormFieldModule,
		MatProgressSpinnerModule,
		MatInputModule,
		MatFormFieldModule,
		MatPaginatorModule,
		MatSortModule,
		MatExpansionModule,
		MatMenuModule
	],
	exports: [
		MatButtonModule,
		MatError,
		MatIconModule,
		MatSidenavModule,
		MatListModule,
		MatTabsModule,
		MatDialogModule,
		MatChipsModule,
		MatDividerModule,
		MatSliderModule,
		MatSelectModule,
		MatRadioModule,
		MatNativeDateModule,
		MatDatepickerModule,
		MatSnackBarModule,
		MatIconModule,
		MatDialogModule,
		MatProgressSpinnerModule,
		MatButtonModule,
		MatSortModule,
		MatTableModule,
		MatTabsModule,
		MatCheckboxModule,
		MatToolbarModule,
		MatCardModule,
		MatFormFieldModule,
		MatProgressSpinnerModule,
		MatInputModule,
		MatFormFieldModule,
		MatPaginatorModule,
		MatButtonToggleModule,
		MatSortModule,
		MatMenuModule,
		MatExpansionModule
	]
})
export class MaterialModule {}
